### ISSUE TITLE
Issues with running requirements.txt 

### ISSUE THREAD

**Issue by deadbeatdandylyon** [prof79/fansly-downloader-ng#103]
So after some trial and error, I tried starting all over with the requirements.txt and found a few problems which I don't know if this is what is causing other issues. 

here is my pip list currently, what I have noticed is that 

pillow==10.2.0 has updated to version 11.0.0 however I am unable to install version 10.2.0
plyvel-ci==1.5.0 Unable to install any version - see second image (i did update my visual C++ - although not sure If I actually needed to, after doing so got a bunch of warning errors

![image](https://github.com/user-attachments/assets/654583e5-5fec-4c2e-a74a-8e2a1488195b)

![image](https://github.com/user-attachments/assets/fbc4fd2b-224f-414c-9846-b8de7e31b853)

**Comment by HetKaTet** [comment]
What did you do to fix this? Im having the same issue with installing the requirements
