### ISSUE TITLE
Memory error followed by LiveError

### ISSUE THREAD

**Issue by jamesltyler9** [prof79/fansly-downloader-ng#14]
## Bug Description
Downloader gets stuck on seemingly empty or deleted post. When going to said post on the website, nothing is there. The downloader says memory error.
After hitting enter, an error showing will show saying the following will appear. It then does this for the remainder of the scrape.

[ [43]ERROR ] [2024-02-02 | 16:33]: Unexpected error during Timeline download: 
Traceback (most recent call last):
  File "download\common.py", line 144, in process_download_accessible_media
  File "download\media.py", line 192, in download_media
  File "rich\progress.py", line 1159, in start
  File "rich\live.py", line 113, in start
  File "rich\console.py", line 836, in set_live
rich.errors.LiveError: Only one live display may be active at once

## Expected behavior
Downloading of all accessible videos to complete.

## Actual behavior
Download of videos halt. 

## Environment Information
 - Operating System: Windows 10
 - Fansly Downloader Version: NG v0.8.4
 - Fansly Downloader Type: Executable
 - Specific creators name: Flashingemma

## User Research

I have done the following:
- [x ] Looked through [old GitHub issues](https://github.com/Avnsx/fansly-downloader/issues?&q=is%3Aissue)
- [ x] Read the [config.ini options](https://github.com/Avnsx/fansly-downloader/wiki/Explanation-of-provided-programs-&-their-functionality#explanation-of-configini)
- [ x] Searched on [Google](https://www.google.com/search?q=how+do+I+foo)

## Additional context

[ Info ] [2024-02-02 | 16:19]: Downloading video '2023-04-29_at_12-21_id_508746034797617152.mp4'
[ [43]ERROR ] [2024-02-02 | 16:33]: Unexpected error during Timeline download: 
Traceback (most recent call last):
  File "download\common.py", line 144, in process_download_accessible_media
  File "download\media.py", line 199, in download_media
MemoryError

[ Info ] [2024-02-02 | 16:33]: Inspecting Timeline cursor: 513164991394750465 [CID: 370924281300787200]
[ Info ] [2024-02-02 | 16:33]: @flashingemma - amount of media in Timeline: 47 (scrapable: 43)
[ Info ] [2024-02-02 | 16:33]: Downloading video '2023-04-30_at_13-46_id_509129828679557120.mp4'
[ [43]ERROR ] [2024-02-02 | 16:33]: Unexpected error during Timeline download: 
Traceback (most recent call last):
  File "download\common.py", line 144, in process_download_accessible_media
  File "download\media.py", line 192, in download_media
  File "rich\progress.py", line 1159, in start
  File "rich\live.py", line 113, in start
  File "rich\console.py", line 836, in set_live
rich.errors.LiveError: Only one live display may be active at once

**Comment by prof79** [comment]
Thanks for all the info, I'm currently ill, I'll come back to you.

**Comment by prof79** [comment]
Thanks a lot! You @jamesltyler9 found another stupid memory bug, the `Rich LiveError` was just a follow-up thing because `Rich` does not properly reset progress when other exceptions occur in-between.

The problem should be gone with [v0.8.10](https://github.com/prof79/fansly-downloader-ng/releases/tag/v0.8.10), please try.
