### ISSUE TITLE
Failed downloading M3U8 at playlist_content request. Response code: 403

### ISSUE THREAD

**Issue by ZincStoat** [prof79/fansly-downloader-ng#17]
Up until a couple of days ago it's all been working fine, my subscriptions are live, I can play videos/view pictures through the browser and fansly-downloader-ng didn't have a problem downloading.
Recent videos though report errors like the following

Attached as text file to avoid auto formatting xml
[errors.txt](https://github.com/prof79/fansly-downloader-ng/files/14199715/errors.txt)

It then goes on to deduplicate/skip all past content. I've checked my authorization_token, updated my user_agent as Chrome had updated, though the script hadn't reported any issues there. I'm wondering whether Fansly have broken something, again.

Happens with more than one creator who've uploaded video recently, but having added a creator I haven't scraped in a while, older videos (up to the end of January at least) seem fine, so I think it's a "new feature".

No issues downloading images that I can see.

Using version 0.8.4

**Comment by JuuuuunArs** [comment]
I also have the same symptom and cannot download certain videos.

**Comment by GITHU8HO** [comment]
Getting the same issue

**Comment by ZincStoat** [comment]
@prof79 are there any debug switches or similar I can add to get more information for you?

**Comment by prof79** [comment]
Thanks @ZincStoat for all the steps and info, there would be `--debug` but I doubt it will be of much help. That must be some header or cookie stuff on Fansly's side to "protect" their stuff better. I'd need to do a live observation/browser tools session.
I'm pretty ill right now with high fever, so I'll come back to y'all in due time.

**Comment by ZincStoat** [comment]
> Thanks @ZincStoat for all the steps and info, there would be `--debug` but I doubt it will be of much help. That must be some header or cookie stuff on Fansly's side to "protect" their stuff better. I'd need to do a live observation/browser tools session. I'm pretty ill right now with high fever, so I'll come back to y'all in due time.

Okay man, thanks. Take care of yourself first and foremost.

**Comment by fl4shforward** [comment]
From what I'm seeing, latest vids seems to have ditched m3u8.
They seem to be split in 2 feeds:
![image](https://github.com/prof79/fansly-downloader-ng/assets/93709591/65ecfc5e-26b6-49fd-b661-1328eb8eff48)

**Comment by DrugiAcc** [comment]
Very quick solution for a single video is to download these 2 resources from a browser and run this PowerShell script if you have ffmpeg:

`ffmpeg -i media-video-avc1-1.mp4 -i media-audio-en-mp4a.40.2-1.mp4 -c:v copy YOUR_VIDEO_NAME.mp4 ; Remove-Item media-video-avc1-1.mp4, media-audio-en-mp4a.40.2-1.mp4`

The resources are suffixed with "-1", which is the highest quality and to change it simply change the video resolution.

**Comment by Troll180** [comment]
Having the same issues, using the newest version, it download pictures without issues but no videos.

**Comment by bssoul** [comment]
@Troll180  I've been having issue with it not downloading 1 specific video in dms. Ran it again yesterday & I'm noticing no vids after Feb 5, 2024 will download, not in messages or timeline. I'll try again tonight and see if the same. 
 prof79 is ill so we'll wait. Can't blame the man for not dealing with it when ill.

**Comment by Troll180** [comment]
> @Troll180 I've been having issue with it not downloading 1 specific video in dms. Ran it again yesterday & I'm noticing no vids after Feb 5, 2024 will download, not in messages or timeline. I'll try again tonight and see if the same. prof79 is ill so we'll wait. Can't blame the man for not dealing with it when ill.

Noticed it stopped downloading vids after Feb 6 for me. And yeah no worries, I wasn't complaining, just saying it was still bugged for me as there was a new version. Hope he get better quick! :)

**Comment by bssoul** [comment]
> > @Troll180 I've been having issue with it not downloading 1 specific video in dms. Ran it again yesterday & I'm noticing no vids after Feb 5, 2024 will download, not in messages or timeline. I'll try again tonight and see if the same. prof79 is ill so we'll wait. Can't blame the man for not dealing with it when ill.
> 
> Noticed it stopped downloading vids after Feb 6 for me. And yeah no worries, I wasn't complaining, just saying it was still bugged for me as there was a new version. Hope he get better quick! :)

What had me going nuts is the vid in dm , that one vid was the only vid not downloading. I didn't realize that I wasn't downloading vids after the 5th. Without knowing how these programs work I have to think some script changes at Fansly to stop the downloading. 

I didn't think you were complaining. I was just saying I can't blame the guy because he's sick.

**Comment by prof79** [comment]
@bssoul you're expected just to say `download_mode = single` in the config, the program will prompt you for the post ID explicitly and there you would just enter the digits as told alone eg. `123451111111111111`

**Comment by Python749** [comment]
Having this same issue. Cannot download 3 videos from 2 different accounts.

**Comment by camereaguy2** [comment]
Seems to be the same issue we're all having, then.
![image](https://github.com/prof79/fansly-downloader-ng/assets/155729325/832f7a77-67fe-49c8-a26a-27e13c620517)

**Comment by bssoul** [comment]
> Seems to be the same issue we're all having, then. ![image](https://private-user-images.githubusercontent.com/155729325/305209934-832f7a77-67fe-49c8-a26a-27e13c620517.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwMjc4NTIsIm5iZiI6MTcwODAyNzU1MiwicGF0aCI6Ii8xNTU3MjkzMjUvMzA1MjA5OTM0LTgzMmY3YTc3LTY3ZmUtNDljOC1hMjZhLTI3ZTEzYzYyMDUxNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxNVQyMDA1NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNmFhMzEzMTI5NTAwZGU1ZTgzYTA4MTNjYjk5ZmE3MTRjN2U3ZGI4MTFkYmVhOTI5ZTkzY2NkOWY5NmI3YTYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6Y6uhX9WK4MH2CBM6eqrvg7XP580gNGsBmKIb_exGoY)

Yes it does. Hoping it can be resolved. Without knowing much about these systems it seems like fansly put some blockers in place. An uneducated guess, lol I have no coding experience at all.

**Comment by ZincStoat** [comment]
Fixed in 0.8.6. Many many thanks @prof79 hope you're feeling better now.

**Comment by bssoul** [comment]
> Fixed in 0.8.6. Many many thanks @prof79 hope you're feeling better now.

Now that's awsome news!

**Comment by prof79** [comment]
@ZincStoat you're quite the quick one :D
Yeah thanks, feeling better - also work caught up on me.

We could have spared us this issue if not for one of the original author's ingenious optimizations, guessing the final M3U8's name ... M3U8s are still used in the Fansly API but they have renamed it a bit so one needs to get the master list first, locate the sub-playlist with the highest resolution et voilà, we get what we had in the first place - a list of MPEG-TS files to download and merge.

**Comment by bssoul** [comment]
> @ZincStoat you're quite the quick one :D Yeah thanks, feeling better - also work caught up on me.
> 
> We could have spared us this issue if not for one of the original author's ingenious optimizations, guessing the final M3U8's name ... M3U8s are still used in the Fansly API but they have renamed it a bit so one needs to get the master list first, locate the sub-playlist with the highest resolution et voilà, we get what we had in the first place - a list of MPEG-TS files to download and merge.

You sure as hell impress me with the speed you get things done, especially when you are sick. 👍

**Comment by ZincStoat** [comment]
> We could have spared us this issue if not for one of the original author's ingenious optimizations

I've been caught out by previous author's cunning but ultimately unsafe tricks in my own programming career so I can sympathise. Great work sir, thanks again.

**Comment by bssoul** [comment]
![image](https://github.com/prof79/fansly-downloader-ng/assets/159801305/f1fa9da6-435c-462f-a12f-989ee884cf69)
Just got this error

**Comment by bssoul** [comment]
![image](https://github.com/prof79/fansly-downloader-ng/assets/159801305/65482d40-4e0a-401e-8352-e0aba78f1cff)

Just got this error , click on continue to try again and it's downloading again

**Comment by prof79** [comment]
> ![image](https://private-user-images.githubusercontent.com/159801305/305224236-65482d40-4e0a-401e-8352-e0aba78f1cff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwMzQ4NjMsIm5iZiI6MTcwODAzNDU2MywicGF0aCI6Ii8xNTk4MDEzMDUvMzA1MjI0MjM2LTY1NDgyZDQwLTRlMGEtNDAxZS04MzUyLWUwYWJhNzhmMWNmZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxNVQyMjAyNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNTg3NzJmMTRjNDliMTE0YWM5ODY2Nzc3ZmM4MzNhZjBjZjU3YTBjY2NiMjQwODNmNDAwNGYwZTZkNmI2YTg4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vD3GLCrv8B7TZ9vI1oS4gHFY8Dudi-PtVSiOMlI__C0)
> 
> Just got this error , click on continue to try again and it's downloading again. I lost the 1 video in the error but seems to have downloaded everything else. It got 100% from messages so it's working great. For the hell of it I'll download again tomorrow & see if I get the error again and if I get the vid.

Yes please, that's interesting ... looks like it stumbled upon an M3U8 that either already was the end or empty, for whatever reason ...

**Comment by bssoul** [comment]
> > ![image](https://private-user-images.githubusercontent.com/159801305/305224236-65482d40-4e0a-401e-8352-e0aba78f1cff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwMzQ4NjMsIm5iZiI6MTcwODAzNDU2MywicGF0aCI6Ii8xNTk4MDEzMDUvMzA1MjI0MjM2LTY1NDgyZDQwLTRlMGEtNDAxZS04MzUyLWUwYWJhNzhmMWNmZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxNVQyMjAyNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNTg3NzJmMTRjNDliMTE0YWM5ODY2Nzc3ZmM4MzNhZjBjZjU3YTBjY2NiMjQwODNmNDAwNGYwZTZkNmI2YTg4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vD3GLCrv8B7TZ9vI1oS4gHFY8Dudi-PtVSiOMlI__C0)
> > Just got this error , click on continue to try again and it's downloading again. I lost the 1 video in the error but seems to have downloaded everything else. It got 100% from messages so it's working great. For the hell of it I'll download again tomorrow & see if I get the error again and if I get the vid.
> 
> Yes please, that's interesting ... looks like it stumbled upon an M3U8 that either already was the end or empty, for whatever reason ...

I'll try it in the am and get back to you as soon as it's done. I just realized something. It was originally a still that she added some moving butterfly wings to. I checked some recent downloads ( I don't toss anything until I know I'm done with it) and it's been downloading with 8.5 & 8.4 maybe it was just an error this time. I'll let you know tomorrow.

Thank you for these upgrades, you're awesome 👍

**Comment by ZincStoat** [comment]
After all that, the creator I was most concerned about missing updates for has announced they're relocating to FanVue because Fansly support are being totally unhelpful. Anyone know a good downloader for FanVue? Ugh. ;)

**Comment by bssoul** [comment]
> > ![image](https://private-user-images.githubusercontent.com/159801305/305224236-65482d40-4e0a-401e-8352-e0aba78f1cff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgwMzQ4NjMsIm5iZiI6MTcwODAzNDU2MywicGF0aCI6Ii8xNTk4MDEzMDUvMzA1MjI0MjM2LTY1NDgyZDQwLTRlMGEtNDAxZS04MzUyLWUwYWJhNzhmMWNmZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxNVQyMjAyNDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNTg3NzJmMTRjNDliMTE0YWM5ODY2Nzc3ZmM4MzNhZjBjZjU3YTBjY2NiMjQwODNmNDAwNGYwZTZkNmI2YTg4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vD3GLCrv8B7TZ9vI1oS4gHFY8Dudi-PtVSiOMlI__C0)
> > Just got this error , click on continue to try again and it's downloading again. I lost the 1 video in the error but seems to have downloaded everything else. It got 100% from messages so it's working great. For the hell of it I'll download again tomorrow & see if I get the error again and if I get the vid.
> 
> Yes please, that's interesting ... looks like it stumbled upon an M3U8 that either already was the end or empty, for whatever reason ...

I'm getting it with 8.7 also but after clicking continue I do get all vids. I'm replying to this again because I just realized I replied to myself earlier.. lol .. Sorry
![image](https://github.com/prof79/fansly-downloader-ng/assets/159801305/54ddd945-caed-4249-bafe-33311405595b)

**Comment by prof79** [comment]
@bssoul lucky me I also caught it with one of my creators now. Seems Fansly in some corner cases hands out empty M3U8 playlists which is the culprit for this. Funnily assuming/guessing there is an 1080p version of it works so [v0.8.8](https://github.com/prof79/fansly-downloader-ng/releases/tag/v0.8.8) now attempts/can download such broken versions to a degree. Don't know if this workaround will work for all variations out there. Please try.

**Comment by bssoul** [comment]
> @bssoul lucky me I also caught it with one of my creators now. Seems Fansly in some corner cases hands out empty M3U8 playlists which is the culprit for this. Funnily assuming/guessing there is an 1080p version of it works so [v0.8.8](https://github.com/prof79/fansly-downloader-ng/releases/tag/v0.8.8) now attempts/can download such broken versions to a degree. Don't know if this workaround will work for all variations out there. Please try.

I'm giving it a try now, I'll let you know how it goes.

Thank you!

**Comment by bssoul** [comment]
> > @bssoul lucky me I also caught it with one of my creators now. Seems Fansly in some corner cases hands out empty M3U8 playlists which is the culprit for this. Funnily assuming/guessing there is an 1080p version of it works so [v0.8.8](https://github.com/prof79/fansly-downloader-ng/releases/tag/v0.8.8) now attempts/can download such broken versions to a degree. Don't know if this workaround will work for all variations out there. Please try.
> 
> I'm giving it a try now, I'll let you know how it goes.
> 
> Thank you!


> @bssoul lucky me I also caught it with one of my creators now. Seems Fansly in some corner cases hands out empty M3U8 playlists which is the culprit for this. Funnily assuming/guessing there is an 1080p version of it works so [v0.8.8](https://github.com/prof79/fansly-downloader-ng/releases/tag/v0.8.8) now attempts/can download such broken versions to a degree. Don't know if this workaround will work for all variations out there. Please try.

v0.8.8 is working great for me.. 
Thank you!
