### ISSUE TITLE
Download fails with 'NoneType' is not iterable

### ISSUE THREAD

**Issue by KyleBro22** [prof79/fansly-downloader-ng#18]
## Bug Description
Download fails with the following error

```
[ Info ] [2024-02-09 | 08:42]: Inspecting Timeline cursor: 12345 [CID: 67890]
[ [42]ERROR ] [2024-02-09 | 08:42]: Unexpected error during parsing Timeline content;
Traceback (most recent call last):
  File "/root/fanslyscraper/fansly-downloader-ng-0.8.4/download/common.py", line 113, in process_download_accessible_media
    media_items += [parse_media_info(state, media_info, post_id)]
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/fanslyscraper/fansly-downloader-ng-0.8.4/media/media.py", line 156, in parse_media_info
    parse_variants(item, content=content, content_type='media', media_info=media_info)
  File "/root/fanslyscraper/fansly-downloader-ng-0.8.4/media/media.py", line 72, in parse_variants
    if not 'Key-Pair-Id' in item.highest_variants_resolution_url:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
```
After pressing enter a couple of times the script started to run again, the error is 6 times in the log with the same text.
I ran the script more than once but got the same error.

## Expected behavior
The script should run through the timeline and download all files

## Actual behavior
The script stops with an error and seems to skip timeline => Missing items: 21 (this may indicate a problem)

## Environment Information
 - Operating System: Ubuntu 22.04.3
 - Fansly Downloader Version: 0.8.4
 - Fansly Downloader Type: source => fansly_downloader_ng.py,  Python 3.11
 - Specific creators name: currently "PetiteNymphet"

## User Research

I have done the following:
- [x] Looked through [old GitHub issues](https://github.com/Avnsx/fansly-downloader/issues?&q=is%3Aissue)
- [x] Read the [config.ini options](https://github.com/Avnsx/fansly-downloader/wiki/Explanation-of-provided-programs-&-their-functionality#explanation-of-configini)
- [x] Searched on [Google](https://www.google.com/search?q=how+do+I+foo)

## Additional context
-

**Comment by prof79** [comment]
Thanks for all the info, I'm currently ill, I'll come back to you.

**Comment by KyleBro22** [comment]
no worries, get well soon

**Comment by prof79** [comment]
Hi,

although you were so explicit - I couldn't reproduce maybe because I'm not subscribed to the creator. But I've included a safety check that hopefully *should* work so please give v0.8.7 a go and give me some feedback. Thanks!

**Comment by KyleBro22** [comment]
Hi,

thanks for the quick fix.
The error is gone but for some reason Iam still missing the 21 items.
Theres no obvious error or skip in the output/log (I also tried --debug but that crashes...)
Ill move the existing files and try to redownload all on the weekend to see if that changes anything.

**Comment by KyleBro22** [comment]
I moved the files and downloaded everything again with v0.8.17, theres still 21 missing items.
Iam not sure what they are but its fine for now, the error mentioned above seems to be resolved.
