### ISSUE TITLE
Problem with downloading m3u8 videos

### ISSUE THREAD

**Issue by prxststr** [prof79/fansly-downloader-ng#2]
Tried to download quite recent (from 20.10.2023) content pics and gifs works well, but videos don't. Although some older posts with m3u8 videos were downloadable.
So after trying to download - i got this:

Traceback (most recent call last):
File "fansly_downloader.py", line 1189, in
File "fansly_downloader.py", line 744, in sort_download
File "fansly_downloader.py", line 618, in download_m3u8
IndexError: tuple index out of range.

**Comment by prof79** [comment]
Hi there,

you have posted to the wrong repository. This is the space for Fansly Downloader NG - fansly_downloader_ng.py.

I see from your line numbers and script name that you are using Avnsx' original version. So please try my version 0.7.3 hosted here at https://github.com/prof79/fansly-downloader-ng/releases - or copy and create what you reported here as an issue at https://github.com/avnsx/fansly-downloader/issues.

If it also throws with my version you can post it here with the updated traceback output. I would, however, require some more info like a creator name/sample page where I could try this myself. Seems I have no creator at hand where video download throws.

Thanks!

**Comment by prxststr** [comment]
Hi!

Sorry, but the issue remains the same.

![image](https://github.com/prof79/fansly-downloader-ng/assets/150543417/a20c2845-0729-4f2f-ac5e-7d3181542104)

**Comment by prof79** [comment]
Thanks! I see what's going wrong. There is no audio stream included but the sloppy code tries to access one anyway and doesn't check. Let me see what I can come up with.

**Comment by prof79** [comment]
@prxststr Please take a look if https://github.com/prof79/fansly-downloader-ng/releases/tag/v0.7.4 fixes your issue.

**Comment by prxststr** [comment]
Hi!
Thanks a lot! It works well.

**Comment by prof79** [comment]
Great! Thanks also for the opportunity to test this functionality. I'll close the issue now.

**Comment by prof79** [comment]
Fixed by commit 16ddb78.

**Comment by Valour549** [comment]
I am using the latest version, but I'm also getting that error after every file it downloads
![image](https://github.com/user-attachments/assets/1c94373c-dde3-4ebd-a1b3-50d292bef987)
