### ISSUE TITLE
Windows defender is detecting Trojan:Win32/Wacatac.B!ml 

### ISSUE THREAD

**Issue by thund3rgun** [prof79/fansly-downloader-ng#22]
In the latest version v0.8.16 Windows Defenders is detecting this trojan. Last version I was using was v0.8.0 and I tried downloading the last few and got the same. Anyone else getting this?
![Screenshot_22](https://github.com/prof79/fansly-downloader-ng/assets/125626630/fc06ff2f-a3e7-48b0-87c3-0445052c4079)

**Comment by heatblast69** [comment]
Hey there, i got the same problem downloading the latest release
![image](https://github.com/prof79/fansly-downloader-ng/assets/58352520/cd49b52f-9a7a-487e-a037-46e650f3e52e)

**Comment by e2489** [comment]
Likely a false positive related to PyInstaller (https://old.reddit.com/r/antivirus/comments/nlubcn/installing_pyinstaller_windows_antivirus_detecs/)

**Comment by prof79** [comment]
There is nothing I can do, all executables are built automatically in GitHub data centers. I heard there were issues in the past and the automated build process has fared much better in that regard but sometimes certain binary patterns cause false positives.
If you're concerned you may wait for the next release.

**Comment by prof79** [comment]
You may try https://github.com/prof79/fansly-downloader-ng/releases/tag/v0.8.17 .

**Comment by thund3rgun** [comment]
Thanks. Yeah I saw in the past something similar but with a different false positive. I am guessing after the windows update it started this because before it wasn't. Appreciate you checking everything looks good.
