### ISSUE TITLE
Fansly_Downloader_NG-Windows-v0.8.17 Tojan detected by various vendors

### ISSUE THREAD

**Issue by Kvothe1970** [prof79/fansly-downloader-ng#24]
**IMPORTANT:** Be sure to replace all ``{{`` template sections ``⚠️}}`` or your issue may be discarded.

## Bug Description
Windows Defender detects Trojan:Win32/Sabsik.RD.A!ml 
Also see https://www.virustotal.com/gui/file/291e3f6a291110eb4610b366b092bfbad5b0617302957fb048e030ea7f0ec41e

## Expected behavior
no threat deteted

## Actual behavior
Threats deteced by AV

*( If applicable, [add screenshots](https://stackoverflow.com/a/14494775/15163882) to help explain your problem. )*

## Environment Information
Win 11 23H2
Latest Defender Signatures

I have done the following:
- [x ] Looked through [old GitHub issues](https://github.com/Avnsx/fansly-downloader/issues?&q=is%3Aissue)
- [x ] Read the [config.ini options](https://github.com/Avnsx/fansly-downloader/wiki/Explanation-of-provided-programs-&-their-functionality#explanation-of-configini)
- [ x] Searched on [Google](https://www.google.com/search?q=how+do+I+foo)

## Additional context
I assume a false positive but would appreciate confirmation

**Comment by prof79** [comment]
The Windows builds are automatically made in a CI-CD pipeline in Github data centers. As can be seen from the source code, it does its job and nothing evil. If you have doubts use the source code version/use build.ps1 to build your own EXE using pyinstaller.

**Comment by Kvothe1970** [comment]
Thanks, just wanted to make sure. I appreciate you taking the time to reply!
