### ISSUE TITLE
Scrapes only messages

### ISSUE THREAD

**Issue by Meeehwhat** [prof79/fansly-downloader-ng#32]
I tried it many times and scrapes only images and videos from messages of that creator. No posts nor PPV.
I am subscribed.

**Comment by prof79** [comment]
Could you provide more info like OS, downloader version, a screenshot/log output? Does this happen with a specific creator or do other creators download properly?

**Comment by Meeehwhat** [comment]
Hi , I found the issue. 
In config where you have to put username. I put username with space at the end. 
I had to delete the space. 
Now it is working.
