### ISSUE TITLE
I can download single or messages but not timelie]

### ISSUE THREAD

**Issue by bssoul** [prof79/fansly-downloader-ng#37]
I downloaded 8.19 and it worked  great with messages and single download but it would not download timeline or normal it said. I follow the creator & I purchase the monthly subscription. 

![Screenshot 2024-03-18 132645](https://github.com/prof79/fansly-downloader-ng/assets/159801305/bda0a3d4-c568-47bd-9880-ed2898305e5b)

**IMPORTANT:** Be sure to replace all ``{{`` template sections ``⚠️}}`` or your issue may be discarded.

## Bug Description
{{ Replace with a clear and concise description of what the bug is. ⚠️}}

## Expected behavior
{{ What did you expect to happen?⚠️}}

## Actual behavior
{{ What actually happened? ⚠️}}

*If applicable, add screenshots (just paste/`CTRL+V` - or see [this guide](https://stackoverflow.com/a/14494775/15163882)) to help explain your problem.*

## Environment Information
 - Operating System: {{e.g. Windows, Linux, macOS ⚠️}}
 - Fansly Downloader Version: {{e.g. v0.4 ⚠️}}
 - Fansly Downloader Type: {{e.g. Executable, python version ⚠️}}
 - Specific creators name: {{e.g. FanslyModelName ⚠️}}

## User Research
*( fill ``[ ]`` with ``x``, if you've already done said task )*

I have done the following:
- [ ] Looked through [old GitHub issues](https://github.com/prof79/fansly-downloader-ng/issues?&q=is%3Aissue)
- [ ] Read the [config.ini options](https://github.com/prof79/fansly-downloader-ng/wiki/Fansly-Downloader-NG-Settings#explanation-of-configini)
- [ ] Searched the Web (like [DuckDuckGo](https://duckduckgo.com))

## Additional context
{{Add any other context about the problem here. ⚠️}}

**Comment by ZincStoat** [comment]
See #34 
In a nutshell, Fansly have moved the goalposts again and broken Timeline downloads. @prof79 is looking into it, and now even @Avnsx has offered some advice. See that thread for updates,

**Comment by bssoul** [comment]
ZincStout Thanks for filling me in.👍

**Comment by prof79** [comment]
Well @bssoul I chimed in as well ;-)

**Comment by prof79** [comment]
Have fun ^^

https://github.com/prof79/fansly-downloader-ng/releases/tag/v0.9.1

**Comment by bssoul** [comment]
Absolutely! You're the man. I just meant it because he showed me where to see your posts on this. I'm reasonably new to github. This and my last time on with a problem are the only two times I've been on.. 
Thank you for all your hard work, it's greatly appreciated!

**Comment by prof79** [comment]
@bssoul yeah sorry and thanks @ZincStoat I didn't even realize that there was a third new issue for the same root cause.

**Comment by bssoul** [comment]
Testing latest version now. Thank you for all you do.👍

**Comment by bssoul** [comment]
It worked for messages but stopped after about 45 vid downloads from timeline. I tried a 2nd time and timeline did not work again.

[ Info ] [2024-03-18 | 20:55]: Executing Timeline functionality. Anticipate remarkable outcomes!
[ Info ] [2024-03-18 | 20:55]: Inspecting most recent Timeline cursor ... [CID: 469230986228408320]
[ [35]ERROR ] [2024-03-18 | 20:55]: Couldn't find any scrapable media at all!                
 This most likely happend because you're not following the creator, your authorisation token is wrong                
 or the creator is not providing unlocked content.
[ Info ] [2024-03-18 | 21:10]: Inspecting most recent Timeline cursor ... [CID: 469230986228408320]
[ [35]ERROR ] [2024-03-18 | 21:10]: Couldn't find any scrapable media at all!                
 This most likely happend because you're not following the creator, your authorisation token is wrong                
 or the creator is not providing unlocked content.

**Comment by bssoul** [comment]
I'd like to add after that failure I got an email telling me I was banned. I'm guessing because I tried it too many times? 3 times. Once on single , Once on normal that stalled after 45 downloads then tried once again and nothing downloaded, was back to same as previous version not finding any content.

**Comment by prof79** [comment]
Discussion went further under #40
