### ISSUE TITLE
randomly stopped downloading

### ISSUE THREAD

**Issue by mrtuxa** [prof79/fansly-downloader-ng#39]
WARNING | 01:52 || Could not find a chat history with hunnypaint; skipping messages download ...
 Info | 01:52 || Executing Timeline functionality. Anticipate remarkable outcomes!

 Info | 01:52 || Inspecting most recent Timeline cursor ... [CID: 330443675492425728]
 [35]ERROR | 01:52 || Couldn't find any scrapable media at all!                
 This most likely happend because you're not following the creator, your authorisation token is wrong                
 or the creator is not providing unlocked content.

**Comment by mrtuxa** [comment]
my subsciption is valid until April 02

**Comment by prof79** [comment]
I'm very sorry, if you still have an active account please try v0.9.3.

**Comment by prof79** [comment]
Please see #34.
