### ISSUE TITLE
my account got terminated

### ISSUE THREAD

**Issue by mrtuxa** [prof79/fansly-downloader-ng#40]
fansly send me that mail, during i tried to download some videos

Hello,
 
We have determined that you have engaged in an egregious violation of our [Terms of Service](https://fansly.com/tos).
 
Specifically, the violation is subject to the following provision:
 

        circumvent, disable, damage, intentionally misuse, or otherwise interfere with the operations of the Company, any User’s enjoyment of Fansly, or any security-related features that prevents, limits, or restricts the use or copying of any materials or that enforces limitations on the use of Fansly, by any means, including posting, linking to, uploading, or otherwise disseminating viruses, adware, spyware, malware, logic bombs, Trojan horses, worms, harmful components, corrupted data, or other malicious codes, files, or programs designed to interrupt, destroy, limit, or monitor the functionality of any computer software or hardware or any telecommunications equipment.
        access or use any automated process (such as a robot, spider, scraper, or similar) to access Fansly in violation of our robot exclusion headers or to scrap all or a substantial part of Fansly (other than in connection with bona fide search engine indexing or as the Company may otherwise expressly permit).

As a result, we have terminated your Fansly account.

Kind regards,

Fansly Team
Fansly.com

**Comment by pirate-cpu** [comment]
Were you running anything else while using the tool like VPN?

**Comment by mrtuxa** [comment]
i dont really use a vpn during downloads

**Comment by cont39** [comment]
Is this why I wouldn't work this morning. It wouldn't work. Not banned yet. Am I going to be?

**Comment by bigxd123** [comment]
> Is this why It wouldn't work this morning. It wouldn't work. I tried Avnsx and then this one and it didn't work? Not banned yet. Am I going to be?

I think thats impossible to say. What is clear though is that they probably flagged all accounts using it. They might just pick a few and ban them to scare users. Especially posting your error log in here with the account you tried to scrape probably makes it easy for them to identify the fansly account for the GitHub user.

I would probably not use an account you care about with any third party tools.

**Comment by cont39** [comment]
Damn I guess time will tell now. Let's see if I get banned or not. Sorry no idea about the legal stuff

**Comment by bigxd123** [comment]
> Damn I guess time will tell now. Let's see if I get banned or not. Sorry no idea about the legal stuff, Hopefully I get just a warning.

just don't post any outputs of the tool publicly that could identify you in case they actually do read this here. These bans are probably strategic.

And ye using third party tools is always risky, especially if they crack down on it like this. Breaking the tool is one thing but flagging users is something even the creator of the tool can't really know / prevent.

**Comment by cont39** [comment]
So now what. Wait for the heat to die down, Then what. What's the alternative to these downloaders? Things would be so simple if we just download the stuff we pay for.

**Comment by bigxd123** [comment]
> So now what. Wait for the heat to die down, Then what. What's the alternative to these downloaders? Things would be so simple if we just download the stuff we pay for. Hold up howd the warning come for you? An email?

Email, ye. Similar to yours just without the termination. And idk what the strategy is. It's a shame, it's thanks to the people that use these tools to leak stuff I guess. But I doubt it'll cool down or at least it's impossible to know without risking your account getting flagged. Maybe if the tools did something against leakers, idk prevent downloading lots of profiles? Idk if fansly would then go easier on it.

**Comment by bssoul** [comment]
I got it & was banned too

**Comment by mrtuxa** [comment]
this issue is also related to this #37

**Comment by prof79** [comment]
I'm terribly sorry to hear that.

They have changed something again - and since they seem to now also terminate accounts using the downloader maybe I should just give up on this. My work is tempting enough and I do not have the time nor fancy to play daily cat-and-mouse with the Fansly security team in my spare time and I also do not have the resources to reverse and code an exact replica of the original web app. I'm a paying customer for some creators and I am not a pirate, just want to use/browse my lib on VR goggles - I guess they totally lack imagination of use cases.

**Comment by bssoul** [comment]
Can't blame you one bit. I'm not going to need it anymore myself. Seems the creator I used it for is also wanting $$ for dm's now. lol I've been paying for her subscription & then buying things from her. I spend like $300 per month & now she wants per dm fee🤣🤣🤣 That just cost her $300 & subscription from me. I wonder what total loss will be when others say bye bye?

**Comment by Bum211** [comment]
I just looked into the Config file and it have a Cache with your Device ID and Timestamp. I guess if you run it it will be tracked. That's probably how they can track you... just a thought. It was good while it lasts. Thank you for all you do @prof79 and @Avnsx!

**Comment by Oldgit13** [comment]
I was lucky I guess. Downloaded version 0.8.19 yesterday it was the latest at the time. Got through the messages ok and hit the timeline with error 35. Double checked the auth details all were correct hit the key to continue bam error 35 again, hit the key one more time and error 35. Came here and saw a new version decided to leave it and try again today and now I see this post. I might create a burner account to experiment not wanting to risk my actual account now.

**Comment by rori54** [comment]
Same error as Oldgit13 doesn't work

**Comment by prof79** [comment]
v0.9.2 is up but probably won't do you any good, feels they changed more behind the scenes.

@Bum211 - you need to cache the device ID because requesting it over and over again from the device/id API will get you blocked from that endpoint with a 429 for some time. However, I do invalidate such cached ID after 3 hours - and you could also just delete the `[Cache]` section from you `config.ini` to get a new one/check your hypothesis.

Btw Fansly should also already know from the authorization token who's account it is.

**Comment by bssoul** [comment]
prof79 I have to laugh, less than an hour ago I was thinking I bet you don't give up because like me when you can't seem to fix something you decide you're going to fix it no matter what🤣🤣🤣
I think I was banned because I did the tests too soon together. I probably should have switched to other pc to at least have different device id.
I'm now considering a different subscription and test it on other pc. I figure I should stay away from this pc for a little bit in case device id is banned. I might try tonight on other pc with diff account of course. I'll keep you informed. 
Thank you for all your hard work👍

**Comment by prof79** [comment]
@bssoul I have a "never give up" poster at work and I usually don't but I have also other interests and there are other sites for such content who even offer downloads, no problem (sometimes w/ higher sub prices for a download sub). Sometimes you have to cover your losses. And interestingly OnlyFans is more prudent in that regard, ofscraper is running and thriving it seems. And also creators seem to have their problems with Fansly.

For experimentation please download/use v0.9.2. I consider it broken but at least you can provide the correct `_checkKey` which was hardcoded before (and is now invalid).

**Comment by e2489** [comment]
I hope you don't give up and there's a way to beat this, just to piss them off if nothing else.

I think this is absolutely ridiculous on Fansly's part. I only subscribed to creators there because I liked the platform, but after this I'm done with them. Almost every creator has an alternative, I'll just use that instead. Seems like everyone is jumping ship anyway, good luck to them spitting in their customers' faces, that always works out well.

**Comment by bssoul** [comment]
My renewal was 7 days ago so I have every intention of chargeback.
I wasn't going to but between them & the girl wanting to do dm fee now I got a little pissed. I was also thinking a good payback is subscribe to her again, never do a dm & never buy or give her a penny again. Kind of like a little slap in the face. lol
On the other hand just not subscribing would do that & lose her sub fee.
I really thought this one was a little smarter & wouldn't do something like this but I was wrong.

**Comment by bssoul** [comment]
@prof79 I will download 9.2 for test.
Thank you once again👍

**Comment by bigxd123** [comment]
@prof79  Maybe try to add things to prevent the heavy abuse they probably only care about. Not sure how that would look but I doubt they care for the single user archiving their stuff and are more after the users abusing tools like this to leak content.

**Comment by e2489** [comment]
> @prof79 Maybe try to add things to prevent the heavy abuse they probably only care about. Not sure how that would look but I doubt they care for the single user archiving their stuff and are more after the users abusing tools like this to leak content.

Sounds like that's exactly what they care about though, they're banning people just for using the tool, not for leaking content.

**Comment by prof79** [comment]
@bssoul I'll hire you as personal prophet, we *might* be back in business ... stupid old me overworked/tired forgot to actually call the essential session setup function I was testing from the outside ... and strangely enough my test run before publishing worked for whatever reason without a proper session variable set 🤦🤦🤦

Few mins and build of v0.9.3 should be complete, please try.

**Comment by bssoul** [comment]
My hero🤣🤣
That will do it, so tired & overworked causes us to miss things sometimes it just doesn't allow us to think of something that we would normally see.

**Comment by hsg120** [comment]
> Few mins and build of v0.9.3 should be complete, please try.

Can confirm--running the scraper now and it works great. No issues at all to report as of this moment.

I really appreciate all of the hard work you've put into this!!

**Comment by bssoul** [comment]
That's great, I was going to try yesterday but didn't get to it. This morning I thought maybe I should wait since I was already banned. Now I know it's safe & I don't have to worry. Thank you for testing it!

**Comment by pirate-cpu** [comment]
I want to try it again. I'm just curious about the people who were banned and if they ever used a VPN while using the site, regardless of whether they were downloading or browsing.

**Comment by hsg120** [comment]
> I want to try it again. I'm just curious about the people who were banned and if they ever used a VPN while using the site, regardless of whether they were downloading or browsing.

Well, just to add an additional datapoint, I am currently using a VPN (PIA).

**Comment by bigxd123** [comment]
> I was one of the banned & I believe it was because I tried it too often in a short time. I did not use vpn. I did a full download test that failed after like 40 downloads, I did messenger test that worked then did a single download test that worked and tried full download again, failed then banned. I think it was my own fault, got too cocky thinking they won't ban.. lol

Ye its a very risky thing and just hoping they actually only care about heavy users. The other person that got banned said they just downloaded very few pictures. So it's just kind of hoping I guess that they only target heavy abusers. At least they will know if you use the tool, lets just all hope they are fine with light personal use.

**Comment by hsg120** [comment]
> > I was one of the banned & I believe it was because I tried it too often in a short time. I did not use vpn. I did a full download test that failed after like 40 downloads, I did messenger test that worked then did a single download test that worked and tried full download again, failed then banned. I think it was my own fault, got too cocky thinking they won't ban.. lol
> 
> Ye its a very risky thing and just hoping they actually only care about heavy users. The other person that got banned said they just downloaded very few pictures. So it's just kind of hoping I guess that they only target heavy abusers. At least they will know if you use the tool, lets just all hope they are fine with light personal use.

Are you able to just create a new account?

**Comment by bigxd123** [comment]
I just hope they don't collect all users now and do ban waves at random times.

**Comment by bssoul** [comment]
Yes two of them, same card to0 using same info, address etc.🤣🤣

**Comment by hsg120** [comment]
> Yes two of them, same card to0 using same info, address etc.🤣🤣

Okay that's good to know!! Glad to hear you're back in business too xD

**Comment by bigxd123** [comment]
> Yes two of them, same card to0 using same info, address etc.🤣🤣

They probably targeted a few users that posted in here to get the word out that the tool is detected. Both of you guys posted your download log and then got banned. They probably wanted you to be vocal about the ban in here to maybe scare others.

Probably the reason why they don't care for you to sign back up. I worked at some companies that did similar tactics.

**Comment by Oldgit13** [comment]
Been wondering how their detection is working. I mean the idea behind this tool is to not make it obvious that you are using it but rather mimic a typical browser request for the content. If it's calling everything correctly then it's going to be pretty hard to tell from normal browser behavior unless you're doing mass scraping from a single account within a short time.

**Comment by bssoul** [comment]
In my case I have to believe it was my own screwup causing it.

**Comment by Oldgit13** [comment]
Lucky despite the error 35 received 3 times on v0.8.19 I escaped your unfortunate situation. So far so good on a burner account with the latest version. Still being cautious with it and will wait a bit more before I resume it on my main account.
