### ISSUE TITLE
[SSL: CERTIFICATE_ VERIFY_FAILED]

### ISSUE THREAD

**Issue by MrAmedeus** [prof79/fansly-downloader-ng#44]
Want to start off by saying this piece of software has been amazing, so thank you!

New here, so hopefully i'm able to provide enough information

**Bug Description:**
I seem to be getting this issue after the newest update to v0.9.3:
RuntimeError: Error during session setup: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)

**Log**
![Screenshot 2024-03-22 at 9 30 14 am](https://github.com/prof79/fansly-downloader-ng/assets/164430154/3ffe4e9f-bd2c-444d-a087-f6a3d31fc1cb)

## Environment Information
 - Operating System: {{Mac OS}}
 - Fansly Downloader Version: {{0.9.3}}

## User Research
*( fill ``[ ]`` with ``x``, if you've already done said task )*

I have done the following:
- [x ] Looked through [old GitHub issues](https://github.com/prof79/fansly-downloader-ng/issues?&q=is%3Aissue)
- [ x] Read the [config.ini options](https://github.com/prof79/fansly-downloader-ng/wiki/Fansly-Downloader-NG-Settings#explanation-of-configini)
- [x ] Searched the Web (like [DuckDuckGo](https://duckduckgo.com))

## Additional context
{{Add any other context about the problem here. ⚠️}}

**Comment by bickman2k** [comment]
Same issue on Arch Linux on 0.9.3.

**Comment by prof79** [comment]
First of all thanks @MrAmedeus didn't even now it is working on macOS now 😊 Have an old MacBook never had the time to check in the past months.

Usually as a sys/sec admin I'd say this is an indication of HTTPS inspection - a proxy or transparent firewall that re-encrypts traffic. Usually in corpo/campus nets but that would also mean your browser has to have that issuer certificate installed or you'd get certificate errors as well.

Other than that could be an esoteric CA in use regarding the Fansly WebSocket endpoint - or something going down the `websockets` package or `openssl`. Have to research whether there is a way to skip validation in code.

**Comment by prof79** [comment]
https://github.com/prof79/fansly-downloader-ng/releases/tag/v0.9.7 should fix the SSL issue (by ignoring it) but you may have a hard time figuring out future check keys, depending on your skill ...

**Comment by MrAmedeus** [comment]
> https://github.com/prof79/fansly-downloader-ng/releases/tag/v0.9.7 should fix the SSL issue (by ignoring it) but you may have a hard time figuring out future check keys, depending on your skill ...

Thanks for that, ill give it a try and get back to you.

In terms of skill level, i wouldn't rate it at all. LOL. I wouldn't know the first thing about check keys, but happy to try figure things out when i have spare time.

**Comment by MrAmedeus** [comment]
The latest update seems to have fixed the issue.

Working on Mac OS Sonoma 14.2.1

Great work!

**Comment by bssoul** [comment]
> https://github.com/prof79/fansly-downloader-ng/releases/tag/v0.9.7 should fix the SSL issue (by ignoring it) but you may have a hard time figuring out future check keys, depending on your skill ...

How are the check keys found?

**Comment by prof79** [comment]
@bssoul please see #34 . I just posted an explanation.
