### ISSUE TITLE
 Make sure, checking the main.js sources of the Fansly homepage, that the `this.checkKey_` value is identical to this

### ISSUE THREAD

**Issue by mediaburnwayne** [prof79/fansly-downloader-ng#45]
OS version is windows 11

seeing this start question in fansly app

 Make sure, checking the main.js sources of the Fansly homepage,
                    that the `this.checkKey_` value is identical to this
                    
          where can I find this value I see the file in image below
![image](https://github.com/prof79/fansly-downloader-ng/assets/79545392/031a19df-3310-4528-9fe1-e3cae62c504a)

but do not see any key values in the headers

I was getting the "Couldn't find any scrapable media at all!"error

Checked auth token and useragent strings that looked good so thinking I may have a mismatch but do not know how to validate

**Comment by prof79** [comment]
Well we're nearing the end of it, see #34 . They keep changing things. The checkKey is now a dynamic expression. And more has changed.

**Comment by hsg120** [comment]
Open the "inspect page" tool.

Log into Fansly.

Look for a *.js item to appear under the "Name" field.

Copy the key value as shown in the attachment. 
![key](https://github.com/prof79/fansly-downloader-ng/assets/7478024/b80d1825-6cf5-4a58-a9d1-a7271ed12121)

**Comment by mediaburnwayne** [comment]
> Open the "inspect page" tool.
> 
> Log into Fansly.
> 
> Look for a *.js item to appear under the "Name" field.
> 
> Copy the key value as shown in the attachment.
> 
> ![key](https://private-user-images.githubusercontent.com/7478024/316165745-50c3460c-45c9-4a40-89b9-31382ca18d28.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExNjI3ODksIm5iZiI6MTcxMTE2MjQ4OSwicGF0aCI6Ii83NDc4MDI0LzMxNjE2NTc0NS01MGMzNDYwYy00NWM5LTRhNDAtODliOS0zMTM4MmNhMThkMjgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjNUMDI1NDQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWUwZjQzZDVhYTFmYmVhZmY5OTBhNGNhNjRjNjA5NDdjY2E0YjU1ZGFkYzFhZGIwMzIxNzdmMTAzZjgzM2JjYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.fizCqx1iK3mhPSzdF4T19yUZJ8KOANSSIjwEejGRf6U)

thanks that was the ticket. got a clean scrape

**Comment by youyinnn** [comment]
The warning is still shown. Are you sure that's the correct check key?
