### ISSUE TITLE
KeyError: 'release_version' in 0.9.6 following launch of program

### ISSUE THREAD

**Issue by hsg120** [prof79/fansly-downloader-ng#46]
## Bug Description
Receive error, "KeyError: 'release_version'" when executing program.

## Expected behavior
Expected the program to run

## Actual behavior
Exits with error, "KeyError: 'release_version'"

## Environment Information
 - Operating System: Arch Linux
 - Fansly Downloader Version: 0.9.6
 - Fansly Downloader Type: Python 3.11
 - Specific creators name: liliafourtwenty
 
![fansly error](https://github.com/prof79/fansly-downloader-ng/assets/7478024/338bb865-6c02-4309-bcd9-738d93a9ae2b)

Is anyone else seeing this error?

**Comment by prof79** [comment]
I hope this is fixed with 0.9.7 but the downloader is getting more and more useless as Fansly continuously changes things to battle the program, see #34 .

**Comment by hsg120** [comment]
> I hope this is fixed with 0.9.7 but the downloader is getting more and more useless as Fansly continuously changes things to battle the program, see #34 .

JFC!! All I want to do is to be able to enjoy this content while I'm offline. Is that really so much to ask?!?

Thank you so much for all of your hard work on this!!

**Comment by prof79** [comment]
> > I hope this is fixed with 0.9.7 but the downloader is getting more and more useless as Fansly continuously changes things to battle the program, see #34 .
> 
> JFC!! All I want to do is to be able to enjoy this content while I'm offline. Is that really so much to ask?!?
> 
> Thank you so much for all of your hard work on this!! =D

Hellyeah, I ask myself the same ...

**Comment by hsg120** [comment]
Update for 0.9.7

I'm getting the following error--

 ERROR | 18:44 || An unexpected error occurred: Error during session setup: 401 Client Error: Unauthorized for url: https://apiv3.fansly.com/api/v1/account/me?ngsw-bypass=true
Traceback (most recent call last):
  File "/home/jordan/fansly-downloader-ng-0.9.7/api/fansly.py", line 352, in setup_session
    _ = self.get_json_response_contents(self.get_client_account_info())
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jordan/fansly-downloader-ng-0.9.7/api/fansly.py", line 508, in get_json_response_contents
    self.validate_json_response(response)
  File "/home/jordan/fansly-downloader-ng-0.9.7/api/fansly.py", line 489, in validate_json_response
    response.raise_for_status()
  File "/home/jordan/fansly-downloader-ng-0.9.7/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://apiv3.fansly.com/api/v1/account/me?ngsw-bypass=true

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jordan/fansly-downloader-ng-0.9.7/fansly_downloader_ng.py", line 198, in <module>
    exit_code = main(config)
![Screenshot from 2024-03-22 18-52-28](https://github.com/prof79/fansly-downloader-ng/assets/7478024/1250acde-e271-4874-989c-5d90274a44c4)

                ^^^^^^^^^^^^
  File "/home/jordan/fansly-downloader-ng-0.9.7/fansly_downloader_ng.py", line 118, in main
    f'Device ID: {config.get_api().device_id} '
                  ^^^^^^^^^^^^^^^^
  File "/home/jordan/fansly-downloader-ng-0.9.7/config/fanslyconfig.py", line 106, in get_api
    self._api = FanslyApi(
                ^^^^^^^^^^
  File "/home/jordan/fansly-downloader-ng-0.9.7/api/fansly.py", line 59, in __init__
    self.setup_session()
  File "/home/jordan/fansly-downloader-ng-0.9.7/api/fansly.py", line 359, in setup_session
    raise RuntimeError(f'Error during session setup: {ex}')
RuntimeError: Error during session setup: 401 Client Error: Unauthorized for url: https://apiv3.fansly.com/api/v1/account/me?ngsw-bypass=true

**Comment by e2489** [comment]
> JFC!! All I want to do is to be able to enjoy this content while I'm offline. Is that really so much to ask?!?

They're under some weird delusion that making content more difficult to download is going to cause people to just keep resubscribing in order to see it. In reality, anyone who cares about that will always find a way, but you'll have pissed them off and potentially lost them as a customer for no reason.

I've turned off auto-renew for every account I follow, and I'll be subscribing to their OF instead from now on. Good job Fansly!

**Comment by purpleemoji** [comment]
I thought I was doing something wrong. Get the exact same error. Good to know!

General question (sorry to be off topic): does this fork have the ability to scrape Fansly "Tiers"?
The Avnsx Fansly script that I used previously would only scrape content that was on the main wall (non-tiered) and if you were to subbed to a special "VIP" or other tier, it would not even see the content.

**Comment by bssoul** [comment]
> I hope this is fixed with 0.9.7 but the downloader is getting more and more useless as Fansly continuously changes things to battle the program, see #34 .

Is this working?

**Comment by prof79** [comment]
Sorry, see #34 for discussions/self-help - Fansly lost me/I don't care anymore.
