### ISSUE TITLE
Is it fine to use the scraper without fear of being banned?

### ISSUE THREAD

**Issue by ForcedToRock** [prof79/fansly-downloader-ng#47]

**Comment by Oldgit13** [comment]
It should be safe but you probably want to set up a burner account and test it on that first before using on your main account. Just to make sure everything goes smoothly and you don't get any errors. Stop if you do and report here if you don't see the issue already posted.

**Comment by prof79** [comment]
Using a tool outside the allowed usage policies of a corporation is always risky similar to leaking/sharing account credentials for sites.

And sorry for the bluntness, I don't really care anymore, Fansly lost me (and my money).
