### ISSUE TITLE
Single mode ignores existing Normal mode directory structure

### ISSUE THREAD

**Issue by ZincStoat** [prof79/fansly-downloader-ng#7]
## Bug Description
Single post mode run on an existing creator's content to check issue with missing media was fixed, which was already divided automatically into Messages and Timeline, it created a new Pictures directory alongside Messages and Timeline, even though it only actually downloaded the images missing from Timeline\Pictures.

## Expected behavior
I expected the missing media to be slotted into Timeline\Pictures

## Actual behavior
A new Pictures directory was created

<img width="1099" alt="image" src="https://github.com/prof79/fansly-downloader-ng/assets/47276979/9a2fa128-771f-4b3b-b9cd-fcc20fc3dffc">

## Environment Information
 - Operating System: Windows 11
 - Fansly Downloader Version: 0.7.7
 - Fansly Downloader Type: Python for Windows 3.11.7
 - Specific creators name: Nope

## Additional context
Since I don't think you can get a Post ID from a message, presumably Single mode would apply only to Timeline posts, so if there is an existing Timeline directory, media for the targeted post would be placed in the appropriate subdirectory off there.

**Comment by blue-popsicle** [comment]
I'm having the same issue, but it occurs with download_mode = Normal. This isn't isolated to Single mode.
I'm using v0.8.7 on Windows 10.

**Comment by prof79** [comment]
I removed that weird logic in [v0.8.9](https://github.com/prof79/fansly-downloader-ng/releases/tag/v0.8.9), please try the both of you @ZincStoat  @blue-popsicle

**Comment by ZincStoat** [comment]
Still seems to be an issue. I've recently added a new creator, downloaded all non-PPV content in Normal mode, then paid for a post and thought I'd check Single mode again in response to the above.
In Single mode it's downloaded to creator_fansly\Videos, the Videos directory being created alongside Messages and Timeline.
So I moved that Videos directory to one side and switched back to Normal mode and re-ran it, and the video in question was fetched to Timeline\Videos.
It's not that big a deal for me, I almost invariably use Normal mode. I'd only used Single in the first place as I was checking an earlier issue was fixed by targeting a single post instead of doing a full Normal run. Just thought you might want to be aware.
Version 0.8.15 by the way. You're really on a roll today huh? ;)

**Comment by prof79** [comment]
Thanks for trying and re-phrasing, I was slow on the uptake 😂

With v0.8.16 comming up in a few mins this will hopefully be fixed for good!

Yeah, wanted to get some things out of my hair, many bumps were just stupid self updater testing :D Funny nobody noticed before.

**Comment by ZincStoat** [comment]
> Funny nobody noticed before.

I regularly encounter bugs in our own software and wonder, "Is anybody even using this? How have they not found this issue?" but on the whole I prefer the quiet life to people beating down the door to get us to fix a problem they _have_ found. :)

**Comment by ZincStoat** [comment]
A Pictures post just showed up so I gave it a try with 0.8.16 Single mode and can happily report they went to Timeline\Pictures. Nice one.

**Comment by blue-popsicle** [comment]
Problem solved for me with v0.8.16 on Windows 10. Thanks!
