### ISSUE TITLE
[Errno 22] Application provided invalid, non monotonically increasing dts to muxer in stream 1

### ISSUE THREAD

**Issue by Poggerslads** [prof79/fansly-downloader-ng#9]
## Bug Description
Error message not found on bugs for downloading a video file in a timeline of a fansly content creator using the executable of the downloader.

## Expected behavior
Downloading of the video

## Actual behavior

Got the following error message displayed :

Application provided invalid, non monotonically increasing dts to muxer in stream 1: 9216 >= 8192

 [43]ERROR | 20:48 || Unexpected error during Timeline download:
Traceback (most recent call last):
  File "download\common.py", line 144, in process_download_accessible_media
  File "download\media.py", line 162, in download_media
  File "download\m3u8.py", line 152, in download_m3u8
  File "av\\container\\output.pyx", line 211, in av.container.output.OutputContainer.mux
  File "av\\container\\output.pyx", line 232, in av.container.output.OutputContainer.mux_one
  File "av\\container\\core.pyx", line 285, in av.container.core.Container.err_check
  File "av\\error.pyx", line 336, in av.error.err_check
av.error.ValueError: [Errno 22] Invalid argument: 'C:\\Users\\XXXX\\Downloads\\Fansly_Downloader_NG-Windows-v0.7.10\\XXXXXX\\Timeline\\Videos\\2023-12-26_at_01-07_id_595820358733410305.mp4'; last error log: [mp4] Application provided invalid, non monotonically increasing dts to muxer in stream 1: 9216 >= 8192

## Environment Information
 - Operating System: Windows
 - Fansly Downloader Version: v0.7.10
 - Fansly Downloader Type: Executable
 - Specific creators name: prefer not to disclose

## User Research

I have done the following:
- [X] Looked through [old GitHub issues](https://github.com/Avnsx/fansly-downloader/issues?&q=is%3Aissue)
- [X] Read the [config.ini options](https://github.com/Avnsx/fansly-downloader/wiki/Explanation-of-provided-programs-&-their-functionality#explanation-of-configini)
- [X] Searched on [Google](https://www.google.com/search?q=how+do+I+foo)

## Additional context
This is an echo of this [bug](https://github.com/Avnsx/fansly-downloader/issues/179) I also opened on Avnsx github, the issue still happens, I don't know what to do, you can PM me for more details if needed

**Comment by prof79** [comment]
Hi, I've been quite busy, sorry. I'll plan to rewrite the video download code as it is also very memory-inefficient (#8). I hope to have something soon. I do fear, however, that this might break existing downloads/de-duplication so videos might download all over again. Parsing and re-muxing the video manually was a hazardous move by Avnsx. I also hope my pyffmpeg will package properly.

**Comment by Poggerslads** [comment]
Best of luck to you then, no issue for the "delay" you do only what you can do in time you have :)

**Comment by prof79** [comment]
Hi, you might try this version but note the warning - try with a different folder or backup your existing creator(s). Though I have some ideas I do not yet have a solution for the de-duplication thing as the files essentially become different files when ffmpeg merges them proper.

Be interesting to know whether the pyffmpeg approach fixes that DTS problem. I still see a potential Linux issue but that shouldn't hurt you on Windows.

https://github.com/prof79/fansly-downloader-ng/releases/tag/ondemand

**Comment by Poggerslads** [comment]
Hello :)
So, I downloaded it, and just pasted my folders and my ini file where the exe was, and as a result the dedup worked, and the file it would not be able to download previously got downloaded properly :) so all good for me :)
Thank you very much
